### ISSUE TITLE
Its not working on kissanime

### ISSUE THREAD

**Issue by Droyk** [Pitmairen/selection-search#24] opened 2016-01-21 13:50 UTC
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.

So it captures the search engine but it can't search the word I selected I tried 20 words but with same result page .........it an extension problems and you can even see it from your own eyes

first go to https://kissanime.to/ then press ctrl+alt+left click and it will tell you the URL you have to use for the search engine

now select any word that related to kiss anime and search it ....and it will not work

and here is the URL that your extension use 
https://kissanime.com/Search/Anime/search/{POSTARGS}=%s
this doesn't work no matter what you select it will only give you a result page ...with only some entries non related to it 

This is the URL I created 
https://kissanime.to/Search/Anime{POSTARGS}keyword=%s{POSTENCODING}UTF-8
but this only works on some words but I don’t know why 
 if you want an example I can give it to you but plz fix this or give me an alternative 

and thanxxx for reading it

**Comment by Pitmairen** [comment] 2016-01-21 14:05
I just tested it using this url:
```
https://kissanime.to/Search/Anime{POSTARGS}keyword=%s{POSTENCODING}UTF-8
```
It seems to work for me. Make sure that the "Use post method" checkmark is checked in the wrench next to the search engine.

**Comment by Droyk** [comment] 2016-01-21 17:40
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Jan 21, 2016, 7:35 PM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/24#issuecomment-173578656 "2016-01-21T14:05:28Z - Replied by Github Comment Enhancer"):
> I just tested it using this url:
> 
>     https://kissanime.to/Search/Anime{POSTARGS}keyword=%s{POSTENCODING}UTF-8
> 
> It seems to work for me. Make sure that the "Use post method" checkmark is checked in the wrench next to the search engine.

i think you didn't read my comment correctly it does search some words but only some words on some websites......for e.g.

here is the video 

i can give more websites examples if you want too i will  have to waste my time a bit but i will do it

**Comment by Pitmairen** [comment] 2016-01-21 21:09
Ok, so it seems to be caused by spaces in the search keyword. When selection "Hai to Gensou no Grimgar" it get replaced by "Hai%20to%20Gensou%20no%20Grimgar.

A quick fix is to just replace "%20"  with a space in this line
https://github.com/Pitmairen/selection-search/blob/master/old/postsearch.js#L49
like this:

```javascript
form.append($('<input type="hidden" name="'+key_value[0]+'" value="'+key_value[1].replace(/%20/g, ' ')+'" />'));
```

This will work until i implement a real fix.

**Comment by Droyk** [comment] 2016-01-22 01:03
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Jan 22, 2016, 2:39 AM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/24#issuecomment-173708507 "2016-01-21T21:09:59Z - Replied by Github Comment Enhancer"):
> Ok, so it seems to be caused by spaces in the search keyword. When selection "Hai to Gensou no Grimgar" it get replaced by "Hai%20to%20Gensou%20no%20Grimgar.
> 
> A quick fix is to just replace "%20"  with a space in this line  
> 
> [https://github.com/Pitmairen/selection-search/blob/master/old/postsearch.js#L49](https://github.com/Pitmairen/selection-search/blob/master/old/postsearch.js#L49)  
> 
> like this:
> 
> <div class="highlight highlight-source-js"><pre><span class="pl-smi">form</span>.<span class="pl-en">append</span>(<span class="pl-en">$</span>(<span class="pl-s"><span class="pl-pds">'</span>&lt;input type="hidden" name="<span class="pl-pds">'</span></span><span class="pl-k">+</span>key_value[<span class="pl-c1">0</span>]<span class="pl-k">+</span><span class="pl-s"><span class="pl-pds">'</span>" value="<span class="pl-pds">'</span></span><span class="pl-k">+</span>key_value[<span class="pl-c1">1</span>].<span class="pl-c1">replace</span>(<span class="pl-sr"><span class="pl-pds">/</span>%20<span class="pl-pds">/</span>g</span>, <span class="pl-s"><span class="pl-pds">'</span> <span class="pl-pds">'</span></span>)<span class="pl-k">+</span><span class="pl-s"><span class="pl-pds">'</span>" /&gt;<span class="pl-pds">'</span></span>));</pre></div> 
> This will work until i implement a real fix.

i think you didn't tell me how should i use this ....how?

**Comment by Pitmairen** [comment] 2016-01-22 06:17
If you want this fix before I release an update you have to manually edit the source code.

But I will release an update that fixes this shortly.

**Comment by Droyk** [comment] 2016-01-22 06:33
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Jan 22, 2016, 11:47 AM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/24#issuecomment-173822284 "2016-01-22T06:17:53Z - Replied by Github Comment Enhancer"):
> If you want this fix before I release an update you have to manually edit the source code.
> 
> But I will release an update that fixes this shortly.

source code mmmmm.okay plz tell me the instructions an i will do it .....

Note i have never done a editing on a source code .so plz tell me the instructions and i will do it for u 
and plz dont say no..i dint say i dont want to do it .i just want some instructions that all thanxxx

**Comment by Pitmairen** [comment] 2016-01-22 06:43
I will release a new version later today so if you don't know how to edit the source you can just wait a few hours until i make a new release.

**Comment by Droyk** [comment] 2016-01-22 08:58
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Jan 22, 2016, 12:13 PM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/24#issuecomment-173825642 "2016-01-22T06:43:17Z - Replied by Github Comment Enhancer"):
> I will release a new version later today so if you don't know how to edit the source you can just wait a few hours until i make a new release.

okay but i didn't said that i don't want to edit it I SAID PLZ ME TELL ME THE INSTRUCTIONS AND I WILL DO IT

**Comment by Pitmairen** [comment] 2016-01-22 15:01
You first download the source from here:
https://github.com/Pitmairen/selection-search/archive/master.zip
Then you modify the line that I showed above. 
Then you open the extension settings page in chrome, click enable developer mode, click load unpacked extension and select the directory that contains the manifest.json file. The extension should now load and be ready for use.

**Comment by Pitmairen** [comment] 2016-01-22 15:19
I have released a new version now: 0.8.11.

After you have got this update the following search url should work:
```
https://kissanime.to/Search/Anime{POSTARGS}keyword={%-s}{POSTENCODING}UTF-8
```

**Comment by Droyk** [comment] 2016-01-22 16:06
thanxx did the trick now it worked but why it cant detect it automatically 
and it still can't do with this url  `https://kissanime.to/Search/Anime{POSTARGS}keyword=%s{POSTENCODING}UTF-8`
but this was auto generated then why the above one didn't worked but the below one worked tell me 

https://kissanime.to/Search/Anime{POSTARGS}keyword={%-s}{POSTENCODING}UTF-8

what's the diff.b/w them

**Comment by Pitmairen** [comment] 2016-01-22 16:27
The difference is "{%-s}" vs "%s".
The first tells the extension not to urlencode the spaces that are in the search string.

Normally when sending the search string to a webserver the string has to be urlencode. This means replacing spaces with "%20" and some other characters as well. The kissamine website does not seem to accept this so  you have to use the new "{%-s}" placeholder in the search url to tell the extension not to urlencode the spaces when sending the search to the kissamine site.

The extension can't autodetect this, so the url has to be modified manually.

**Comment by Droyk** [comment] 2016-01-23 12:09
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Jan 22, 2016, 9:57 PM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/24#issuecomment-173968381 "2016-01-22T16:27:08Z - Replied by Github Comment Enhancer"):
> The difference is "{%-s}" vs "%s".  
> 
> The first tells the extension not to urlencode the spaces that are in the search string.
> 
> Normally when sending the search string to a webserver the string has to be urlencode. This means replacing spaces with "%20" and some other characters as well. The kissamine website does not seem to accept this so  you have to use the new "{%-s}" placeholder in the search url to tell the extension not to urlencode the spaces when sending the search to the kissamine site.
> 
> The extension can't autodetect this, so the url has to be modified manually.

so why don't you put it this way add a box and write or update all the url's you seem to be not working in automatic way like this 
http://i.imgur.com/aPGePkg.png

**Closed** 2016-01-25 16:28 UTC
