### ISSUE TITLE
This extension may have been corrupted.

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#2] opened 2015-04-13 18:13 UTC
I've been getting "This extension may have been corrupted." notice at least 3 times a day now, since the update from 0.7.22, so every time i'd repair it and then import my exported data again.
Chrome, x64.

**Comment by bugreport0** [comment] 2015-04-13 18:20
this is my settings if that'd help..

**Comment by Pitmairen** [comment] 2015-04-13 18:26
Does it happen if you disable the synchronization settings?

I probably has something to do with the chunked sync of search engines that was added in version 0.7.21/22.

**Comment by bugreport0** [comment] 2015-04-13 18:30
Gonna disable it and try it again for a bit, and get back to you...

**Comment by Pitmairen** [comment] 2015-04-13 19:02
You don't have enough search engines to make the splitting into chunks kick in. So it may not be the problem after all. 

What version of chrome are you using?
Have you tried uninstalling and reinstalling the extension?

**Comment by bugreport0** [comment] 2015-04-13 19:11
I don't quite get it? do you recommend removing the splitters then?
They have been working without any problem on version 0.7.22.
Chrome, 42.0.2311.82 beta-m (64-bit).

**Comment by Pitmairen** [comment] 2015-04-13 19:35
No it has nothing to do with the splitters. If someone have a lot of search engines and trying to store them in the chrome sync storage the size will exceed the limits of the sync storage. So if there is a lot of engines, before storing the engines in the sync storage, they are split into chunks to prevent hitting the size limit. But this is handled internally in the extension so there is nothing the user has to think about.  

But you don't have enough search engines configured to make this part of the code kick in so it should't be the problem. But i guess we will just have to wait and see if the corruption still happens when sync is disabled.

**Comment by bugreport0** [comment] 2015-04-13 19:47
Oh, i get it now..
I've disabled all the Sync settings, hope the extension would work normally from now on.
Thank you.

**Comment by bugreport0** [comment] 2015-04-13 19:58
It has just been crashed again.
If i had to take a guess (I'm not a programmer or anything) 
but as far as i remember this problem started to appear when i changed the the "Popup Menu" activation from "Auto" to "Left mouse click"
the reason is a bit silly, but when i installed the extension "Magic actions for Youtube", whenever i select a video's title on Youtube, the "auto small button" would be under the extension's banner so it would be unreachable, z-index?
anyway, what do you recommend now?

**Comment by Pitmairen** [comment] 2015-04-13 20:36
So this has been happening since 0.7.22 which was released almost a year ago?

Can you try to download this: https://github.com/Pitmairen/selection-search/archive/master.zip
unpack it somewhere and go to chrome://extensions/ and enable developer mode and click "Load unpacked extension" and select the folder you extracted from the zip file. Then load your settings into this extension and see if it still gets corrupted.

**Comment by bugreport0** [comment] 2015-04-13 21:42
Works like a charm so far..!

**Comment by bugreport0** [comment] 2015-04-14 09:13
So, I hope you have put your finger on the problem..

**Comment by Pitmairen** [comment] 2015-04-14 09:34
No, the code on the link above is exactly the same code that is published on the web store. :)

I don't think the problem is with the extension code. I think it's a problem with your chrome install. It is probably some old data in the cache related to the extension that is causing the problem.  

Maybe you could try to clear some browser data: https://support.google.com/chrome/answer/95582?hl=en

And/or uninstall the extension and look for any data related to the extension in the data folder:
```
Windows
C:\Users\<Your_User_Name>\AppData\Local\Google\Chrome\User Data\Default
Linux
~/.config/google-chrome/Default
~/.config/chromium/Default
```
The extension has id: gipnlpdeieaidmmeaichnddnmjmcakoe

**Comment by bugreport0** [comment] 2015-04-14 10:33
I've already uninstalled it several times before, and cleared the cache and cookies of the entire browser before re-installing it again.
I've also deleted my old exported settings and made them again from scratch.
still crashes anyway!
Is it possible that the extension has a conflict with other extension/s, "ublock" or something?
Anyway, appreciate your help.

**Comment by Pitmairen** [comment] 2015-04-14 11:07
Yes it could be a conflict with another extension. You can try to disable all extension except for selection search and see if it still crashes. 

If is still crashes when only selection search is enabled you can try to create a new chrome user profile and install the extension in that profile and see if it still crashes.

**Comment by Droyk** [comment] 2016-01-23 17:30
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Apr 14, 2015, 4:37 PM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/2#issuecomment-92771540 "2015-04-14T11:07:35Z - Replied by Github Comment Enhancer"):
> Yes it could be a conflict with another extension. You can try to disable all extension except for selection search and see if it still crashes. 
> 
> If is still crashes when only selection search is enabled you can try to create a new chrome user profile and install the extension in that profile and see if it still crashes.

I am not seeing these on my 4 computers so i think this is fixed plz close this issue down [Pitmairen](https://github.com/Pitmairen)

**Closed** 2016-01-25 20:26 UTC
